"""create_purchasing_tables

Revision ID: 1f67dc1129d5
Revises: 76684ebb563d
Create Date: 2026-07-25 22:08:19.983607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f67dc1129d5'
down_revision: Union[str, Sequence[str], None] = '76684ebb563d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('yield_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('yield_unit_id', sa.UUID(), nullable=False),
    sa.Column('output_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['output_ingredient_id'], ['ingredients.entity_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['yield_unit_id'], ['units_of_measure.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_recipes_name', 'recipes', ['name'], unique=False)
    op.create_table('production_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'in_progress', 'completed', 'cancelled', name='productionorderstatus'), nullable=False),
    sa.Column('quantity_to_produce', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_index('ix_production_orders_recipe_id', 'production_orders', ['recipe_id'], unique=False)
    op.create_index('ix_production_orders_source_location_id', 'production_orders', ['source_location_id'], unique=False)
    op.create_index('ix_production_orders_status', 'production_orders', ['status'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('recipe_id', 'ingredient_id', name='uq_recipe_ingredient')
    )
    op.create_index('ix_recipe_ingredients_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('production_order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('order_id', 'ingredient_id', name='uq_production_order_line')
    )
    op.create_index('ix_production_order_lines_order_id', 'production_order_lines', ['order_id'], unique=False)
    op.create_table('yield_records',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('expected_yield', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('actual_yield', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yield_records')
    op.drop_index('ix_production_order_lines_order_id', table_name='production_order_lines')
    op.drop_table('production_order_lines')
    op.drop_index('ix_recipe_ingredients_recipe_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_production_orders_status', table_name='production_orders')
    op.drop_index('ix_production_orders_source_location_id', table_name='production_orders')
    op.drop_index('ix_production_orders_recipe_id', table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index('ix_recipes_name', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
