"""feat(catalog): initial schema

Revision ID: 236d84cd7616
Revises: 
Create Date: 2026-07-25 14:58:36.073495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236d84cd7616'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('units_of_measure',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('unit_type', sa.Enum('weight', 'volume', 'unit', 'length', name='unittype'), nullable=False),
    sa.Column('base_unit_id', sa.UUID(), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units_of_measure.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('unit_of_measure_id', sa.UUID(), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allergen_info', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_sku'), 'ingredients', ['sku'], unique=True)
    op.create_table('supplier_ingredients',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('supplier_id', 'ingredient_id', name='uq_supplier_ingredient')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_ingredients')
    op.drop_index(op.f('ix_ingredients_sku'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('units_of_measure')
    op.drop_table('suppliers')
    op.drop_table('categories')
    # ### end Alembic commands ###
