"""create_sales_and_waste_tables

Revision ID: 429c2be5ac93
Revises: 1f67dc1129d5
Create Date: 2026-07-25 22:42:26.608393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429c2be5ac93'
down_revision: Union[str, Sequence[str], None] = '1f67dc1129d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sales_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('dine_in', 'takeaway', 'delivery', 'online', name='saleschannel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'in_preparation', 'ready', 'delivered', 'cancelled', name='salesorderstatus'), nullable=False),
    sa.Column('table_reference', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_sales_orders_channel', 'sales_orders', ['channel'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=True)
    op.create_index('ix_sales_orders_source_location_id', 'sales_orders', ['source_location_id'], unique=False)
    op.create_index('ix_sales_orders_status', 'sales_orders', ['status'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('order_id', 'ingredient_id', name='uq_sales_order_line')
    )
    op.create_index('ix_sales_order_lines_order_id', 'sales_order_lines', ['order_id'], unique=False)
    op.create_table('waste_records',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('waste_category_id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('waste_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['waste_category_id'], ['waste_categories.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('movement_id')
    )
    op.create_index('ix_waste_records_category_id', 'waste_records', ['waste_category_id'], unique=False)
    op.create_index('ix_waste_records_ingredient_id', 'waste_records', ['ingredient_id'], unique=False)
    op.create_index('ix_waste_records_location_id', 'waste_records', ['location_id'], unique=False)
    op.create_index('ix_waste_records_waste_date', 'waste_records', ['waste_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waste_records_waste_date', table_name='waste_records')
    op.drop_index('ix_waste_records_location_id', table_name='waste_records')
    op.drop_index('ix_waste_records_ingredient_id', table_name='waste_records')
    op.drop_index('ix_waste_records_category_id', table_name='waste_records')
    op.drop_table('waste_records')
    op.drop_index('ix_sales_order_lines_order_id', table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index('ix_sales_orders_status', table_name='sales_orders')
    op.drop_index('ix_sales_orders_source_location_id', table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_number'), table_name='sales_orders')
    op.drop_index('ix_sales_orders_channel', table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_table('waste_categories')
    # ### end Alembic commands ###
