"""create_inventory_tables

Revision ID: 66c4d4505f27
Revises: b3f1a2c9d4e8
Create Date: 2026-07-25 17:05:19.450496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c4d4505f27'
down_revision: Union[str, Sequence[str], None] = 'b3f1a2c9d4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('location_type', sa.Enum('warehouse', 'fridge', 'freezer', 'bar', 'production', name='locationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_table('batches',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.entity_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_batches_ingredient_location_expiry', 'batches', ['ingredient_id', 'location_id', 'expiry_date'], unique=False)
    op.create_table('stock_items',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('ingredient_id', 'location_id', name='uq_stock_item')
    )
    op.create_table('stock_movements',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('entry', 'exit', 'adjustment', 'transfer_out', 'transfer_in', 'waste', 'production_consumption', 'sales_deduction', 'physical_count', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.entity_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_stock_movements_ingredient_location', 'stock_movements', ['ingredient_id', 'location_id'], unique=False)
    op.create_index('ix_stock_movements_type', 'stock_movements', ['movement_type'], unique=False)
    op.create_table('kardex_entries',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('movement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('movement_type', sa.Enum('entry', 'exit', 'adjustment', 'transfer_out', 'transfer_in', 'waste', 'production_consumption', 'sales_deduction', 'physical_count', name='movementtype'), nullable=False),
    sa.Column('quantity_in', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_out', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_value_change', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('movement_id')
    )
    op.create_index('ix_kardex_ingredient_location_date', 'kardex_entries', ['ingredient_id', 'location_id', 'movement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kardex_ingredient_location_date', table_name='kardex_entries')
    op.drop_table('kardex_entries')
    op.drop_index('ix_stock_movements_type', table_name='stock_movements')
    op.drop_index('ix_stock_movements_ingredient_location', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('stock_items')
    op.drop_index('ix_batches_ingredient_location_expiry', table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
