"""create_purchasing_tables

Revision ID: 76684ebb563d
Revises: 8d86dbdfd406
Create Date: 2026-07-25 21:48:03.329848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76684ebb563d'
down_revision: Union[str, Sequence[str], None] = '8d86dbdfd406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'partially_received', 'received', 'cancelled', name='postatus'), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_purchase_orders_supplier_id', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'completed', 'cancelled', name='receiptstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_goods_receipts_order_id', 'goods_receipts', ['order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receipt_number'), 'goods_receipts', ['receipt_number'], unique=True)
    op.create_table('purchase_invoices',
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'matched', 'disputed', 'paid', name='invoicestatus'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_purchase_invoices_invoice_number'), 'purchase_invoices', ['invoice_number'], unique=True)
    op.create_index('ix_purchase_invoices_order_id', 'purchase_invoices', ['order_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('order_id', 'ingredient_id', name='uq_po_line')
    )
    op.create_index('ix_po_lines_order_id', 'purchase_order_lines', ['order_id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('receipt_id', 'ingredient_id', name='uq_receipt_line')
    )
    op.create_index('ix_receipt_lines_receipt_id', 'goods_receipt_lines', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipt_lines_receipt_id', table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index('ix_po_lines_order_id', table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index('ix_purchase_invoices_order_id', table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_number'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_goods_receipts_receipt_number'), table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_order_id', table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index('ix_purchase_orders_supplier_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
