"""create_transfer_tables

Revision ID: 8d86dbdfd406
Revises: 66c4d4505f27
Create Date: 2026-07-25 20:51:30.201176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d86dbdfd406'
down_revision: Union[str, Sequence[str], None] = '66c4d4505f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_counts',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'cancelled', name='physicalcountstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_physical_counts_location_id', 'physical_counts', ['location_id'], unique=False)
    op.create_table('transfers',
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_transit', 'completed', 'cancelled', name='transferstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_transfers_transfer_number'), 'transfers', ['transfer_number'], unique=True)
    op.create_table('physical_count_lines',
    sa.Column('count_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('system_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['physical_counts.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('count_id', 'ingredient_id', name='uq_count_line')
    )
    op.create_index('ix_physical_count_lines_count_id', 'physical_count_lines', ['count_id'], unique=False)
    op.create_table('transfer_lines',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('requested_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('transferred_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.entity_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.entity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('transfer_id', 'ingredient_id', name='uq_transfer_line')
    )
    op.create_index('ix_transfer_lines_transfer_id', 'transfer_lines', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_lines_transfer_id', table_name='transfer_lines')
    op.drop_table('transfer_lines')
    op.drop_index('ix_physical_count_lines_count_id', table_name='physical_count_lines')
    op.drop_table('physical_count_lines')
    op.drop_index(op.f('ix_transfers_transfer_number'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_physical_counts_location_id', table_name='physical_counts')
    op.drop_table('physical_counts')
    # ### end Alembic commands ###
